CREATE TABLE MM_BANCOS(
codEntidad char(5) PRIMARY KEY,
banco varchar2(80) NOT NULL,
nombrebanco varchar2(20) NOT NULL,
TipoEntidad varchar2(34) NOT NULL,
TipoCompetencia varchar2(22) NOT NULL,
TipoCompetencia2 varchar2(22) NOT NULL
);

CREATE TABLE MM_UBIGEOS(
UBIGEO CHAR(6) PRIMARY KEY,
DEPARTAMENTO VARCHAR2(15) NOT NULL,
PROVINCIA VARCHAR2(30) NOT NULL,
DISTRITO VARCHAR2(36) NOT NULL,
CODIGO CHAR(6) NULL,
DISTRITO_DET VARCHAR2(30) NOT NULL,
FLGZONA CHAR(4) NOT NULL,
CENTROSNEGOCIO VARCHAR2(14) NULL,
FLGPROVCENTROSNEGOCIO VARCHAR2(100) NULL,
DISTRITO_AGG VARCHAR(30) NULL,
FLGCIUDAD CHAR(1) NOT NULL
);

CREATE TABLE MM_ONPE(
NumDoc VARCHAR2(8) PRIMARY KEY,
DigVer CHAR(1) NULL,
GrpVot VARCHAR2(10) NOT NULL,
Ubigeo CHAR(6) NULL,
ApPaterno CHAR(2) NOT NULL,
ApMaterno CHAR(2) NOT NULL,
Nombres VARCHAR2(33) NULL,
FecNac CHAR(8) NOT NULL,
Sexo CHAR(1) NULL,
GrdInst VARCHAR2(64) NOT NULL,
edad INT NULL
);
ALTER TABLE MM_ONPE
CONSTRAINT FK_MM_ONPE_MM_UBIGEOS_01 FOREIGN KEY(Ubigeo) REFERENCES MM_UBIGEOS;

CREATE TABLE MM_CLIENTES(
PERIODO CHAR(6) NOT NULL,
TIP_REG VARCHAR2(10) NULL,
COD_SBS_CLI INT NOT NULL,
FEC_REPORTE CHAR(8) NOT NULL,
TIP_DOC_TRI CHAR(1) NULL,
RUC CHAR(11) NULL,
TIP_DOC_IDE CHAR(1) NULL,
DOC_IDENTIDAD VARCHAR2(8) NULL,
TIP_PERSONA CHAR(1) NOT NULL,
TIP_EMPRESA CHAR(1) NULL,
CAN_EMPRESA INT NOT NULL,
DEU_CALIF0 NUMBER(6,2) NOT NULL,
DEU_CALIF1 NUMBER(6,2) NOT NULL,
DEU_CALIF2 NUMBER(6,2) NOT NULL,
DEU_CALIF3 NUMBER(6,2) NOT NULL,
DEU_CALIF4 NUMBER(6,2) NOT NULL,
RAZ_SOC_O_AP CHAR(2) NOT NULL,
APE_MATERNA CHAR(2) NOT NULL,
APE_CASADA CHAR(2) NOT NULL,
NOMBRE1 CHAR(2) NOT NULL,
NOMBRE2 CHAR(2) NOT NULL
);
ALTER TABLE MM_CLIENTES
CONSTRAINT FK_MM_CLIENTES_MM_ONPE_01 FOREIGN KEY (DOC_IDENTIDAD) REFERENCES MM_ONPE;

CREATE TABLE MM_DEUDAS(
PERIODO CHAR(6) NOT NULL,
TIP_REG VARCHAR2(10) NULL,
COD_SBS_CLI INT NOT NULL,
COD_EMPRESA CHAR(5) NOT NULL,	
TIP_CREDITO CHAR(2) NOT NULL,
COD_CUENTA CHAR(14) NOT NULL,
CONDICION VARCHAR2(4) NOT NULL,
SALDO NUMBER(8,2) NOT NULL,
CLASIFICACION CHAR(1) NOT NULL,
SITCRE CHAR(1) NULL,
TARJ CHAR(1) NULL,
SLDVIG CHAR(1) NULL
);
ALTER TABLE MM_DEUDAS
CONSTRAINT FK_MM_DEUDAS_MM_BANCOS_01 FOREIGN KEY (COD_EMPRESA) REFERENCES MM_BANCOS;
ALTER TABLE MM_DEUDAS
CONSTRAINT FK_MM_DEUDAS_MM_CLIENTES_02 FOREIGN KEY (COD_SBS_CLI) REFERENCES MM_CLIENTES;