OPTIONS (SKIP=1)
LOAD DATA 
INFILE 'Deudas_RCCs.txt'
TRUNCATE PRESERVE BLANKS
INTO TABLE MM_DEUDAS
fields terminated by '	'
OPTIONALLY ENCLOSED BY '"' 
TRAILING NULLCOLS
(
PERIODO,
TIP_REG,
COD_SBS_CLI,
COD_EMPRESA "LPAD(:COD_EMPRESA,5,0)",	
TIP_CREDITO,	
COD_CUENTA,	
CONDICION,	
SALDO,	
CLASIFICACION,	
SITCRE,	
TARJ,	
SLDVIG
)